<?php

namespace App\Filament\Pages;

use App\Filament\Support\TranslatableField;
use App\Models\Setting;
use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Filament\Forms;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Pages\Page;

/**
 * Site-wide SEO defaults — applied as a fallback whenever a page doesn't set
 * its own "Deskripsi Meta (SEO)" (see PageResource), plus settings that only
 * make sense once per site (canonical domain, Google verification, robots
 * indexing switch). Consumed by the frontend's shared `useSeo()` hook, which
 * merges this with each page's own title/meta_description before writing the
 * document <head>.
 *
 * HasPageShield gates this page behind the `page_SeoSettings` permission
 * (generated by `php artisan shield:generate`) — without it, any logged-in
 * admin could open it by URL regardless of role.
 */
class SeoSettings extends Page implements HasForms
{
    use HasPageShield;
    use InteractsWithForms;

    protected static ?string $navigationIcon = 'heroicon-o-magnifying-glass';

    protected static ?string $navigationLabel = 'Pengaturan SEO';

    protected static ?string $title = 'Pengaturan SEO';

    protected static ?string $navigationGroup = 'Navigasi Website';

    protected static ?int $navigationSort = 25;

    protected static string $view = 'filament.pages.site-settings';

    public ?array $data = [];

    public function mount(): void
    {
        $record = Setting::current();

        $this->form->fill($record->only($record->getFillable()));
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Meta Deskripsi & Kata Kunci Bawaan')
                    ->description('Dipakai untuk halaman mana pun yang belum diisi "Deskripsi Meta (SEO)" sendiri di menu Halaman.')
                    ->schema([
                        ...TranslatableField::textarea(
                            'seo_default_meta_description',
                            'Deskripsi Meta Bawaan',
                            rows: 3,
                            placeholder: 'Ringkasan singkat tentang sekolah untuk hasil pencarian Google',
                        ),
                        ...TranslatableField::text(
                            'seo_keywords',
                            'Kata Kunci (pisahkan dengan koma)',
                            placeholder: 'sekolah islam, tk islam bandung, sd islam bandung',
                        ),
                    ])
                    ->columns(2),

                Forms\Components\Section::make('Gambar Bagikan (Open Graph)')
                    ->description('Gambar pratinjau saat link situs dibagikan di WhatsApp, Facebook, atau Twitter/X — dipakai jika halaman belum punya gambar sendiri.')
                    ->schema([
                        Forms\Components\FileUpload::make('seo_default_og_image')
                            ->label('Gambar Bagikan Bawaan')
                            ->image()
                            ->directory('settings')
                            ->helperText('Ukuran ideal 1200x630px.')
                            ->columnSpanFull(),
                        Forms\Components\TextInput::make('seo_twitter_handle')
                            ->label('Username Twitter / X')
                            ->placeholder('@alihsanislamicsch'),
                    ])
                    ->columns(2),

                Forms\Components\Section::make('Lanjutan')
                    ->schema([
                        Forms\Components\TextInput::make('seo_canonical_domain')
                            ->label('Domain Resmi Situs')
                            ->url()
                            ->placeholder('https://alihsanislamicsch.co.id')
                            ->helperText('Dipakai untuk link canonical & og:url. Tanpa garis miring di akhir.'),
                        Forms\Components\TextInput::make('seo_google_site_verification')
                            ->label('Kode Verifikasi Google Search Console')
                            ->placeholder('Isi nilai "content" dari tag meta verifikasi Google'),
                        Forms\Components\Toggle::make('seo_robots_index')
                            ->label('Izinkan mesin pencari mengindeks situs ini')
                            ->helperText('Matikan sementara saat situs masih dalam tahap pengembangan/staging.')
                            ->default(true)
                            ->columnSpanFull(),
                    ])
                    ->columns(2),
            ])
            ->statePath('data');
    }

    public function save(): void
    {
        Setting::current()->update($this->form->getState());

        Notification::make()
            ->title('Pengaturan SEO tersimpan')
            ->success()
            ->send();
    }
}
