<?php

namespace App\Filament\Pages;

use App\Filament\Support\TranslatableField;
use App\Models\Setting;
use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Filament\Forms;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Pages\Page;

/**
 * Single-record settings screen (logo, navbar top bar, footer) so the
 * frontend's navbar/footer/logo follow whatever the admin sets here instead
 * of being hardcoded — ships with defaults matching the original hardcoded
 * design (see Setting::current()) so nothing changes until someone edits it.
 *
 * HasPageShield gates this page behind the `page_SiteSettings` permission
 * (generated by `php artisan shield:generate`) — without it, any logged-in
 * admin could open it by URL regardless of role.
 */
class SiteSettings extends Page implements HasForms
{
    use HasPageShield;
    use InteractsWithForms;

    protected static ?string $navigationIcon = 'heroicon-o-swatch';

    protected static ?string $navigationLabel = 'Pengaturan Situs';

    protected static ?string $title = 'Pengaturan Situs';

    protected static ?string $navigationGroup = 'Navigasi Website';

    protected static ?int $navigationSort = 20;

    protected static string $view = 'filament.pages.site-settings';

    public ?array $data = [];

    public function mount(): void
    {
        $record = Setting::current();

        $this->form->fill($record->only($record->getFillable()));
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Logo & Identitas Situs')
                    ->schema([
                        Forms\Components\FileUpload::make('logo')
                            ->label('Logo')
                            ->image()
                            ->directory('settings')
                            ->live()
                            ->helperText('Kosongkan untuk memakai logo bawaan.')
                            ->columnSpanFull(),
                        ...TranslatableField::text('site_name', 'Nama Situs', required: true, placeholder: 'Al-Ihsan Islamic School'),
                        ...TranslatableField::text('site_tagline', 'Tagline', placeholder: 'National & Singapore - Based Curriculum...'),
                    ])
                    ->columns(2),

                Forms\Components\Section::make('Bar Atas (Topbar)')
                    ->description('Baris kecil paling atas navbar, sebelum menu utama.')
                    ->schema([
                        ...TranslatableField::text('topbar_message', 'Pesan Selamat Datang', placeholder: 'Selamat datang di ...'),
                        Forms\Components\TextInput::make('topbar_phone')
                            ->label('Nomor Telepon')
                            ->placeholder('+62 813-2097-5696'),
                        Forms\Components\TextInput::make('topbar_email')
                            ->label('Email')
                            ->email()
                            ->placeholder('administrasi@alihsanislamicsch.co.id'),
                    ])
                    ->columns(2),

                Forms\Components\Section::make('Footer')
                    ->schema([
                        ...TranslatableField::textarea('footer_description', 'Deskripsi Singkat', rows: 3),
                        ...TranslatableField::text(
                            'footer_copyright',
                            'Teks Hak Cipta',
                            placeholder: '© {year} Al-Ihsan Islamic School — Hak cipta dilindungi.',
                        ),
                        Forms\Components\TextInput::make('social_website')
                            ->label('Link Website')
                            ->url()
                            ->placeholder('https://alihsanislamicsch.co.id'),
                        Forms\Components\TextInput::make('social_facebook')
                            ->label('Link Facebook')
                            ->url()
                            ->placeholder('https://facebook.com/...'),
                        Forms\Components\TextInput::make('social_twitter')
                            ->label('Link Twitter / X')
                            ->url()
                            ->placeholder('https://twitter.com/...'),
                    ])
                    ->columns(2),
            ])
            ->statePath('data');
    }

    public function save(): void
    {
        Setting::current()->update($this->form->getState());

        Notification::make()
            ->title('Pengaturan situs tersimpan')
            ->success()
            ->send();
    }
}
